version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: discord
      MARIADB_USER: sacha
      MARIADB_PASSWORD: ahcas

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080